### ISSUE TITLE
New template events architecture

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#10997]
_Extracted the following description from #10924 - let's keep track of this feature in this issue._

We aim to replace our current template events system using Sonata Block bundle and improve both the developer experience using it and Sylius extendability, especially in the light of [Sylius Store](https://sylius.com/plugins/) which has been recently opened.

## Keeping track of changes

 - [x] Initial implementation (started with #10924, refactored in #10988, added more functionality in #10991, refactored further in #11036, and another in #11059)
 - [x] Replace existing `sonata_block_render_event` method calls with `sylius_template_event`(started with topbar in #10991, continued with homepage in #11014)
    - [x] Register blocks that will keep backwards compatibility and call `sonata_block_render_event`
    - [x] Merge existing `*.before_something` and `*.after_something` events into `*.something` and use them for core functionalities as well (so that one can add a block in the middle of core ones or disable it)
 - [x] Write more extensive documentation for template events
 - [x] Consider creating [ADR (Architecture Decision Record)](https://github.com/joelparkerhenderson/architecture_decision_record) detailing the reasoning, alternatives and pros/cons of this solution
 - [x] Create _best practices_ guide (what priorities to use in your application / your plugin) so that Sylius ecosystem can adopt it without struggles
   - Initial convention: https://github.com/Sylius/Sylius/pull/10991/files#r362234318
 - [x] Increase discoverability of events and blocks:
    - [x] Debugging commands for CLI (show all registered events, show all blocks for an event) (#10989)
    - [x] HTML comments with event / block names before rendered content (#10988, #11036)
    - [x] Symfony Profiler / Data Collector (#10990)
 - [x] Create issues in downstream repositories making use of current events implementation

## Current implementation

 - We use Sonata Block bundle to create extension points in Sylius, which are recommended to be used by our plugins.

 - An extension point is created by calling `sonata_block_render_event` Twig function:

    ```twig
    {{ sonata_block_render_event('sylius.admin.order.show.before_summary', {'resource': resource}) }}

    <div class="ui segment">
        {% include '@SyliusAdmin/Order/Show/_summary.html.twig' %}
    </div>

    {{ sonata_block_render_event('sylius.admin.order.show.after_summary', {'resource': resource}) }}
    ``` 

 - A block can be injected by creating a template and registering a event listener in DIC:

    ```yaml
    services:
        my.service.name.rendering.block:
            class: Sylius\Bundle\UiBundle\Block\BlockEventListener
            arguments:
                - 'template.html.twig'
            tags:
                - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.order.show.before_summary, method: onBlockEvent }
    ```

    The most obvious issue here is the need to put so much boilerplate code and to concatenate the event name with `sonata.block.event.*` prefix.

 - In order to pass any variable from the template to the rendered blocks, it needs to be defined in `sonata_block` configuration:

    ```yaml
    sonata_block:
        blocks:
            sonata.block.service.template:
                settings:
                    resource: ~
    ```

    After passing a variable to the context, it has to be accessed using `block.settings.*` prefix:

    ```twig
    {{ dump(block.settings.resource) }}
    ```

 - The only possibility to remove a previously registered block is to add a compiler pass removing the listener service that adds it.

 - There's no possibility to change rendering order of blocks.

## Proposed implementation

 - Pure Twig implementation is used, no event listeners for increased performance.
 - An extension point is created by calling `sylius_template_event` Twig function:

    ```twig
    {{ sylius_template_event('sylius.admin.order.show.before_summary', {'resource': resource}) }}

    <div class="ui segment">
        {% include '@SyliusAdmin/Order/Show/_summary.html.twig' %}
    </div>

    {{ sylius_template_event('sylius.admin.order.show.after_summary', {'resource': resource}) }}
    ```

 - A block can be injected by configuring UiBundle:

    ```yaml
    sylius_ui:
        events:
            sylius.admin.order.show.before_summary:
                blocks:
                    some_block: 'template.html.twig' # short syntax
                    another_block: # long syntax
                        template: 'another.html.twig' 
    ```

 - It is possible to pass any variable from the template to the block without any configuration changes.

    It can be accessed using the same variable name:

    ```twig
    {{ dump(resource) }}
    ```

 - It is possible to remove a block by disabling it in the config (assuming the configuration mentioned above comes from some Sylius plugin):

    ```yaml
    # Your application configuration
    sylius_ui:
        events:
            sylius.admin.order.show.before_summary:
                blocks:
                    some_block: false # short syntax
                    another_block: # long syntax
                        enabled: false
    ```

 - It is possible to change the template of some block:

    ```yaml
    # Your application configuration
    sylius_ui:
        events:
            sylius.admin.order.show.before_summary:
                blocks:
                    some_block: 'my_other_template.html.twig'
    ```

 - It is possible to define priorities for blocks, allowing plugin creators and e-commerce developers to change blocks order easily or inject a block in the middle of other ones:

    ```yaml
    # Vendor configuration
    sylius_ui:
        events:
            sylius.admin.order.show.before_summary:
                blocks:
                    first_block: 'first.html.twig' # default priority is 0
                    last_block: 
                        template: 'last.html.twig'
                        priority: -5

    # Your application configuration
    sylius_ui:
        events:
            sylius.admin.order.show.before_summary:
                blocks:
                    middle_block: 
                        template: 'middle.html.twig'
                        priority: -3  # between 0 (first_block) and -5 (last_block)
    ```

 - Having an easy way to disable and reorder blocks, we can merge events like `before_header` and `after_header` into one `header` event with proper priorities. This way we can use event blocks for core Sylius templates and allow for simpler customisations like changing the order of sidebar menus in order show page in admin: 

    <img width="339" alt="Screenshot 2019-12-11 at 14 40 14" src="https://user-images.githubusercontent.com/1897953/70626172-36157e00-1c24-11ea-907d-4eb3042fbd32.png">

    This sidebar can consist of four blocks - customer info, addresses, payment, shipment - that can be manipulated easily.

**Comment by anthid** [comment]
I'm right now working with templates, so I've been thinking about this. I really like it, so here are my ideas to try to make it even better. I can anticipate two uncovered scenarios:

### Scenario 1 (Complex container layout)

Let's say we have some blocks listening to a certain event, and each block comes from a different plugin. They are inserted one after another according to their priority. And we want to achieve the following markup after our event block has been parsed (pretty common if we want to retain control on how our site is shown):

```html
<div class="row">
    <div class="col-6">
        {{block1}}
    </div>
    <div class="col-6">
        <div class="row">
            <div class="col-2">
                {{block2}}
            </div>
            <div class="col-10">
                {{block3}}
            </div>
        </div>
    </div>
</div>
```

To achieve this, we can remove the event placeholder and simply put this markup and include each event block template inside it. But it would be better if we can avoid that solution because we need to override the container template. So, to solve this scenario, we can save that markup as an event template, overriding default blocks rendering:

```yaml
sylius_ui:
  events:
    sylius.event:	
      template: 'custom_markup.html.twig' (the above markup)
      blocks:
        ...
```

That way we can get a custom layout without overriding any block or container template. The bad side of it is that we have to keep that template in sync with our event blocks configuration. One possible solution would be to render undefined blocks before or after that template, based on block priority.

### Scenario 2 (Injecting at block level)

Up until now we are solving how to inject blocks inside containers, but there are scenarios where we want to inject (or remove) small bits inside already existing blocks. In this example [(_address.html.twig)](https://github.com/Sylius/BootstrapTheme/blob/master/SyliusShopBundle/views/Common/Form/_address.html.twig) I only want to remove `{{form_row(form.company)}}` (for B2C), or add a `{{form_row(form.tax_id)}}` after company (for B2B), but currently we have to override the entire template to achieve this.

Setting predefined extension points at every possible place makes no sense, but we can get elements id as selectors to achieve almost infinite extension points. So, to remove `{{form_row(form.company)}}` field:

```yaml
sylius_ui:
  extensions:
    address.form.block.id: (the block id containing our target element)
      company_field_id: (target element selector)
        enabled: false
```

And to inject `{{form_row(form.tax_id)}}`:

```yaml
sylius_ui:
  extensions:
    address.form.block.id: (the block id containing our target element)
      company_field_id: (target element selector)
        blocks:
          some_block: 
            template: 'tax_id_field.html.twig'
            priority: 10
```

That way we don't need to override the entire template just to make tiny changes. How to implement it is another history... :smile:

**Comment by pamil** [comment]
Thanks for the ideas @anthid! 🎉 I'm not sure if we can implement those in the nearest future, but we'll take them into the consideration after we finish transforming from Sonata block events to Sylius template events (we aim to finish it before 1.7.0 release).

There's one major update pending to the overall template infrastructure in #11059, after it gets merged I'll update the opening comment.

**Comment by michalsemelka** [comment]
Hi @pamil 

sorry if it does not belong here, but I was wondering how can I reproduce such behavior like in the EE plugin https://github.com/stefandoorn/sylius-google-tag-manager-enhanced-ecommerce-plugin/blob/v0.10.0/src/EventListener/ProductShowBlockAfterProductHeaderListener.php since you deprecated `Sylius\Bundle\UiBundle\Block\BlockEventListener`? 

We use this listener to add additional data or process data via services quite a lot in our projects. What is other way around? 
I don't like idea of Twig Extension since it is registered globally and I typically need _this_ only for one template. Other idea is to use partial render via subrequests but we try to avoid this as much as possible for performance reasons.

Thank you!

**Comment by gabiudrescu** [comment]
+1 at the question asked by @michalsemelka 

cc @CoderMaggie since @pamil watch has ended.
