### ISSUE TITLE
New Sylius API on API Platform

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#11250]
This issue is created to coordinate efforts and have one space to reference to all of the PR's aiming to provide API platform support for Sylius.

## Sylius API Architecture

Every time you will contribute to Sylius API please, take into account the following decisions (ADRs):
- [API - Product Option Value](https://github.com/Sylius/Sylius/blob/master/adr/2020_03_03_api_product_option_values.md)
- [API - Translations](https://github.com/Sylius/Sylius/blob/master/adr/2020_03_03_api_translations.md)
- [Feature Coverage in API](https://github.com/Sylius/Sylius/blob/master/adr/2020_03_03_feature_coverage_in_api.md)

If you would like to add something there feel free to open a new proposal :) 

**This effort is being done in the current Sylius `master` branch. Please help us with testing what's been done, by using the API locally** 🚀

## TODO for the community - Admin API coverage

If you can't wait to see Sylius with the full API Platform support, feel more than welcome to help us with it. All of these will require to have behat coverage (@ui tagged scenarios run also tagged as @api) to merge them to master. 

- [x]  **Locales** #11273 
All the features from `features/locale/managing_locales`
2 scenarios / 3 files
Create an index action only (show may be required as well)

- [x] **Association Types** #11319 
All the features from: `features/product/managing_product_association_types`
12 scenarios / 8 files
Full CRUD for options and values + validation and filtering

- [x] **Countries** #11278, #11431
All the features from `features/addressing/managing_countries`
15 scenarios / 8 files 
Full CRUD for countries and provinces + validation

- [x] **Zones** #11372
All the features from `features/addressing/managing_zones`
20 scenarios, 7 files
Full CRUD
Ensure proper zone type validation

- [ ] **Taxonomies**
All the features from `features/taxonomy`
47 scenarios, 14 files
Full CRUD
Only features with `@ui` and without `@todo` tag

- [ ] **Channels** #11417, #11486
All the features from `features/user/managing_channels`
35 scenarios, 19 files (16 scenarios/4 files already done)
Full CRUD

- [x] **Tax rates** #14811
All the features from `features/taxation/managing_tax_rates`
18 scenarios, 6 files
Full CRUD

- [ ] **Modifying Order's address**
All the features from `features/order/managing_orders/modifying_billing_address` and `features/order/managing_orders/modifying_shipping_address`
18 scenarios, 10 files

- [ ] **Filtering on the Orders list**
All the features from `features/order/managing_orders/order_filtration`
12 scenarios, 3 files

- [ ] **Order details**
All the features from `features/order/managing_orders/order_details`
30 scenarios, 22 files

- [ ] **Browsing orders**
All the features from `features/order/managing_orders/browsing_orders`
8 scenarios, 6 files

- [ ] **Handling shipments and payments**
All the features from `features/order/managing_orders/handling_order_payment` and `features/order/managing_orders/handling_order_shipment`
15 scenarios, 7 files

If you will cover some of the features above, let us know, so the effort will not be duplicated. More features will be added in the nearest future

**Comment by pamil** [comment]
Thanks for compiling this list, Łukasz! 🎉

**Comment by mmenozzi** [comment]
As [discussed on Slack](https://sylius-devs.slack.com/archives/C3EGDG9LY/p1595315189466900), I think we should clarify if this new API (with API Platform) will be also a shop/frontend API. If the goal is to improve the Sylius PWA capabilities a shop/frontend API is mandatory.

Once we have clarified this we can discuss how to implement these APIs. Should we proceed with unified API routes that behave differently depending on authentication status or user type? Or should we have admin API routes separated from frontend ones?

**Comment by pjedrzejewski** [comment]
@lchrusciel WDYT about renaming this issue to indicate that it's an invitation to contribute to the Admin API? I reference it in the meta-issue about the overall effort: https://github.com/Sylius/Sylius/issues/12466

**Comment by zairigimad** [comment]
Hello, Is there a plan to add the Inventory to the API?

**Comment by vvasiloi** [comment]
Hello,
The Admin API also had endpoints for managing the customers ([docs](https://github.com/Sylius/SyliusAdminApiBundle/blob/master/docs/customers.md)).
Should it be added to the list?
It looks like it's not covered by Behat tests: https://github.com/Sylius/Sylius/tree/4e37f162c8fad574ef5a459ec7c941f1e6d20a7f/features/user/managing_customers

**Comment by NoResponseMate** [comment]
We've kind of forgotten about this issue, but all the parts listed above have been covered in 1.13.

The AdminAPI is complete 🎉
