### ISSUE TITLE
The road to PHP 8.0

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#12298]
It's high time to take care of PHP 8.0 support for Sylius, here's the list of dependencies that need to be upgraded first:

- [x] `friends-of-behat/mink`
- [x] `friends-of-behat/mink-browserkit-driver`
- [x] `friends-of-behat/mink-extension`
- [x] `friends-of-behat/symfony-extension`
- [x] `friends-of-behat/variadic-extension`
- [x] `friendsofsymfony/oauth-server-bundle` (https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/672, not needed after AdminApiBundle is moved out of the core)
- [x] `friendsofsymfony/oauth2-php` (https://github.com/FriendsOfSymfony/oauth2-php/issues/123, not needed after AdminApiBundle is moved out of the core)
- [x] `lchrusciel/api-test-case` (https://github.com/lchrusciel/ApiTestCase/pull/179)
- [x] `liip/imagine-bundle` (https://github.com/liip/LiipImagineBundle/issues/1354)
- [x] `payum/payum`
- [x] `payum/payum-bundle` (https://github.com/Payum/PayumBundle/pull/524 - waiting for tag)
- [x] `php-http/guzzle6-adapter`
- [x] `polishsymfonycommunity/symfony-mocker-container` (https://github.com/PolishSymfonyCommunity/SymfonyMockerContainer/pull/15: it's a test-only dependency, could we replace it?)
- [x] `sspooky13/yaml-standards`
- [x] `stof/doctrine-extensions-bundle` (#12371)
- [x] `sylius-labs/association-hydrator`
- [x] `sylius-labs/coding-standard`
- [x] `sylius-labs/doctrine-migrations-extra-bundle`
- [x] `sylius/grid-bundle`
- [x] `sylius/registry`
- [x] `sylius/resource-bundle`
- [x] `sylius/theme-bundle`
- [x] `willdurand/hateoas-bundle` (https://github.com/willdurand/BazingaHateoasBundle/pull/95)
- [x] `winzou/state-machine`
- [x] `winzou/state-machine-bundle` (https://github.com/winzou/StateMachineBundle/pull/62)
- [x] `zendframework/zend-hydrator`
- [x] `zendframework/zend-stdlib`

**Comment by goetas** [comment]
FYI https://github.com/willdurand/BazingaHateoasBundle/releases/tag/2.2.0 with php8 support

**Comment by vasilvestre** [comment]
@pamil https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/139 do you think you could allow Sylius install with PHP 8.0 through a pre-release ?

**Comment by vasilvestre** [comment]
oauth-server-bundle PHP 8.0 compatibility is available through "2.0.x-dev" [friendsofsymfony/oauth-server-bundle](FriendsOfSymfony/FOSOAuthServerBundle#672)

**Comment by vasilvestre** [comment]
https://github.com/FriendsOfSymfony/oauth2-php/issues/123
Oauth2 has been merged :)

**Comment by pamil** [comment]
Would be perfect to get the OAuth Bundle tagged so that we don't have to use dev version.

**Comment by vasilvestre** [comment]
> Would be perfect to get the OAuth Bundle tagged so that we don't have to use dev version.

https://github.com/FriendsOfSymfony/oauth2-php/pull/125#issuecomment-814347778 this is done ! thank you for such a fast release @GuilhemN :)

**Comment by pamil** [comment]
v1.10.0-ALPHA.1 with PHP 8 support has been released, we could consider this one done, thanks all for contributing 🎉
