### ISSUE TITLE
[Roadmap] Shop API with API Platform completed

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#12466]
Hi! 😃 

The purpose of this issue is to better orchestrate and complete the effort of migration to the new API with the API Platform. I'd love to hear your thoughts, feedback and challenge my thinking about this. :) Also, if you are up for contribution, let us know in the comment so that we do not duplicate efforts.

Definition of done and current progress from my perspective and some open questions:

**Sylius Core**:
- [x] ApiBundle (new) has ~90% feature parity with ShopApiPlugin and can replace it
- [ ] ApiBundle provides a clear API to better support API-first payment gateways

Open Questions:
- Do you have some preference for how to handle payments via API? How do you handle it right now?
- If you have used the new API already, what are the most common customization you have made and what was your experience?
- What are your benchmarks for great APIs?

**Sylius SDKs**
- [ ] At least one SDK provided to consume Sylius API

I think this is a must-have for any headless platform and would open Sylius to the ecosystem of frontend developers, who are not familiar with Symfony. :) There was something for ShopAPIPlugin: https://www.npmjs.com/package/lin3s-sylius-shop-api-client

Open Questions:
- Do you have some thoughts on this? Do you use an SDK already?

**Documentation**:
- [x] There is a public [API Reference](https://master.demo.sylius.com/api/v2/docs)
- [ ] Minimal [tutorial](https://docs.sylius.com/en/latest/api/index.html) for frontend developers published, explaining how to get products and add to cart
- [ ] [Getting Started with Sylius](https://docs.sylius.com/en/latest/getting-started-with-sylius/index.html#getting-started-with-sylius) tutorial includes API examples
- [ ] Minimally sufficient migration guide from ShopAPIPlugin to ApiBundle published
- [x] All references to AdminApiBundle and ShopApiBundle moved to section clearly marked as "legacy"
- [x] "Customizing API Endpoints" added to [The Customization Guide](https://docs.sylius.com/en/latest/customization/api.html)
- [x] The "Custom Paths in new API" article included in a proper [Customization Guide](https://docs.sylius.com/en/latest/customization/api.html) "How to customize paths in the API?"

Open Questions:
- What other documentation would you like to see (or contribute 😉 ) related to the new API?

PS. If you would like to contribute to the admin part of the new API, please see this issue opened by @lchrusciel: https://github.com/Sylius/Sylius/issues/11250

**Comment by lchrusciel** [comment]
Relates to https://github.com/Sylius/Sylius/issues/12453

**Comment by kayue** [comment]
In my project I made a complete custom checkout API to replace Sylius' mutli-step workflow. The payment integration part look like the following.

First we have a single endpoint for developer to create and update the cart. The nice thing about this API is we allow developer to update only part of the order, for example only submit `email` or `shippingAddress`. 

```http
PUT /api/v1/carts/{{ cart_token  }}

{
	"email": "abcd@example.com",
	"items": [
		{
			"sku": "men-white-ss-t-shirts-55XXL",
			"quantity": 1
		}
	],
	"shippingAddress": {
		"firstName": "Sherlock",
		"lastName": "Holmes",
		"street": "KC100",
		"city": "Kwai Hing",
		"countryCode": "HK",
		"postcode": "000",
		"phoneNumber": "123"
	}
}
```

And second there is a specific endpoint to retrieve payment methods, and their `integrationData` for SDK integration.

```http
GET /api/v1/carts/{token}/payment-methods

{
  "methods": [
    {
      "code": "berrics_credit_card",
      "name": "Credit Card",
      "gatewayConfig": {
        "factoryName": "stripe_card",
        "gatewayName": "berrics_stripe_card"
      },
      "integrationData": {
        "liveMode": false,
        "clientSecret": "pi_XXX_secret_XXX",
        "publishableKey": "pk_test_XXX"
      }
    },
    {
      "gatewayConfig": {
        "factoryName": "braintree",
        "gatewayName": "braintree_paypal"
      },
      "code": "paypal",
      "name": "PayPal",
      "integrationData": {
        "token": "XXX==",
        "clientId": "XXX-XXX_XXX"
      }
    }
  ]
}
```

Last step is to complete the cart. Developer should provide `paymentMethod` and `paymentData` in this API, and it might redirect user to paypal's page to complete the payment.

Similar to the first step, developer can optionally update the order information in this step. For example provide a new billing address. In this checkout API we will update the order first according to the given information before we start the checkout flow.

```http
PUT /api/v1/carts/{token}/checkout HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "xxx",
  "billingAddress": {  },
  "paymentMethod": "braintree",
  "paymentData": {
    "nonce": "fake-valid-nonce"
  }
}
```

The goal of my custom API is to allow developer to create an order in (almost) one call.

**Comment by mysiar** [comment]
By headless ecommerce I understand the shop provides API and whole frontend in whatever technology someone wants to choose
Startup point might be Api-Platform https://api-platform.com/docs/client-generator/
where right now there are 7 different libs/frameworks to scafold whole client

**Comment by davidroberto** [comment]
Hi!

Getting the products by a taxon slug should be included in the new API. Maybe by changing the existing "productTaxons.taxon.code" filter in the product resource with a filter accepting the slug of a translated taxon?

**Comment by CoderMaggie** [comment]
@davidroberto it has been recently covered with API here - https://github.com/Sylius/Sylius/pull/12534 ;)
