### ISSUE TITLE
PHP 7.4 syntax

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#12891]
This issue is created to coordinate efforts and have one space to reference to all of the PR's aiming to use PHP7.4 syntax in Sylius

## Hello, folks! 👋 

I've decided to open this issue, to be transparent with our efforts to finally use PHP 7.4 syntax on all Sylius' supported repositories. Let's face the truth - it's _a little bit_ late 💃 But, on the other hand, better late than never 🐎 

I already started the work, with [this PR](https://github.com/Sylius/SyliusResourceBundle/pull/328) on **SyliusResourceBundle**. The path I chose is to use [rectorphp](https://github.com/rectorphp/rector), as it's working spectacularly with the code syntax upgrade. There are some things needed to be done additionally (probably upgrading **PHPStan** or other coding-standard relate libraries), but it should not be a big problem.

Feel free to participate, if you like to 🎉 I'm also sure, that we can do better (and faster) when we decide to bump the minimal PHP version to 8.0 (active support of PHP 7.4 ends at the end of November ⚠️) 💪 

### To-do:

- [x] https://github.com/Sylius/SyliusResourceBundle/ - https://github.com/Sylius/SyliusResourceBundle/pull/328
- [x] https://github.com/Sylius/SyliusGridBundle/ - https://github.com/Sylius/SyliusGridBundle/pull/171
- [x] https://github.com/Sylius/SyliusMailerBundle/ (bump to PHP 7.4 needed as well) - https://github.com/Sylius/SyliusMailerBundle/pull/99
- [x] https://github.com/Sylius/SyliusThemeBundle - https://github.com/Sylius/SyliusThemeBundle/pull/110
- [x] https://github.com/Sylius/SyliusFixturesBundle (bump to PHP 7.4 needed as well) - https://github.com/Sylius/SyliusFixturesBundle/pull/66
- [x] https://github.com/Sylius/Sylius/ - https://github.com/Sylius/Sylius/pull/13012, https://github.com/Sylius/Sylius/pull/13038, https://github.com/Sylius/Sylius/pull/13039, https://github.com/Sylius/Sylius/pull/13040, https://github.com/Sylius/Sylius/pull/13116
- [x] https://github.com/Sylius/SyliusDemo/ - https://github.com/Sylius/SyliusDemo/pull/210
- [x] https://github.com/Sylius/PayPalPlugin/ (bump to PHP 7.4 needed as well) - https://github.com/Sylius/PayPalPlugin/pull/211
- [x] https://github.com/Sylius/RefundPlugin/ - https://github.com/Sylius/RefundPlugin/pull/330
- [x] https://github.com/Sylius/InvoicingPlugin/ - https://github.com/Sylius/InvoicingPlugin/pull/249

Live long and prosper, Sylius Community 🖖 🚀

**Comment by Zales0123** [comment]
We can consider it done 🖖
