### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#13274]
### Internal Packages

- [x] Addressing
- [x] Attribute
- [x] Channel
- [x] Core
    - [x] Sylius/Sylius#14078 
- [x] Currency
- [x] Customer
- [x] Inventory
- [x] Locale
- [x] Order
- [x] Payment
- [x] Product
- [x] Promotion
- [x] Review
- [x] Shipping
- [x] Taxation
- [x] Taxonomy
- [x] User
    - [x] Sylius/Sylius#14068  

### Internal Bundle

- [x] AddressingBundle https://github.com/Sylius/Sylius/runs/6809340436?check_suite_focus=true
    - [x] Sylius/Sylius#13975
    - [x] Sylius/Sylius#14034 
    - [x] Sylius/Sylius#14065
- [x] AdminBundle (🦀 needs sylius/core-bundle) https://github.com/Sylius/Sylius/runs/6776689949?check_suite_focus=true#step:8:19
    - [x] Sylius/Sylius#14191 
    - [x] Sylius/Sylius#14192
    - [x] Sylius/Sylius#14287 
- [x] ApiBundle
    - [x] Sylius/Sylius#14042
    - [x] Sylius/Sylius#14284
- [x] AttributeBundle
    - [x] Sylius/Sylius#13976
- [x] ChannelBundle
    - [x] Sylius/Sylius#13977 
- [x] CoreBundle (🦀 needs sylius/order-bundle, and sylius/theme-bundle)
    - [x] Sylius/Sylius#14184 
    - [x] Sylius/Sylius#14136
- [x] CurrencyBundle
    - [x] Sylius/Sylius#13978 
- [x] CustomerBundle
    - [x] Sylius/Sylius#13979 
- [x] InventoryBundle
    - [x] Sylius/Sylius#13980 
- [x] LocaleBundle
    - [x] Sylius/Sylius#13981 
- [x] MoneyBundle
    - [x] Sylius/Sylius#13982 
- [x] OrderBundle (:heavy_check_mark: Fixed with following PRs)
    - [x] Sylius/Sylius#14066
    - [x] Sylius/Sylius#14113
- [x] PaymentBundle
    - [x] Sylius/Sylius#13983
- [x] PayumBundle  (:heavy_check_mark: Fixed with this following PR)
    - [x] Sylius/Sylius#14182
- [x] ProductBundle
    - [x] Sylius/Sylius#13989
    - [x] Sylius/Sylius#13990 
    - [x] Sylius/Sylius#13991 
- [x] PromotionBundle
    - [x] Sylius/Sylius#14064 
    - [x] Sylius/Sylius#14134
    - [x] Sylius/Sylius#14135
- [x] ReviewBundle
    - [x] Sylius/Sylius#14089 
- [x] ShippingBundle
    - [x] Sylius/Sylius#14063 
- [x] ShopBundle (🦀 needs sylius/core-bundle)
    - [x] Sylius/Sylius#14187
    - [x] Sylius/Sylius#14186
    - [x] Sylius/Sylius#14285 
- [x] TaxationBundle
    - [x] Sylius/Sylius#13992 
    - [x] Sylius/Sylius#14015 
- [x] TaxonomyBundle 
    - [x] Sylius/Sylius#13993 
- [x] UiBundle
    - [x] Sylius/Sylius#13994 
    - [x] Sylius/Sylius#13995 
- [x] UserBundle
    - [x] Sylius/Sylius#14080 
    - [x] Sylius/Sylius#14074 

### Internal PRs
- [x] Sylius/Sylius#13251 
- [x] Sylius/Sylius#14052
- [x] Sylius/Sylius#14054
- [x] Sylius/Sylius#14283
- [x] Sylius/Sylius#14183
- [x] Sylius/Sylius#14256
- [x] Sylius/Sylius#14258
- [ ] Sylius/Sylius#13969

### Sylius technical packages

- [x] sylius-labs/association-hydrator [on master]
- [x] sylius-labs/doctrine-migrations-extra-bundle
    - [x] SyliusLabs/DoctrineMigrationsExtraBundle#12
- [x] sylius-labs/polyfill-symfony-framework-bundle
    - [x] https://github.com/SyliusLabs/PolyfillSymfonyFrameworkBundle/pull/1 
    - [x] https://github.com/SyliusLabs/PolyfillSymfonyFrameworkBundle/pull/2
- [x] sylius-labs/polyfill-symfony-security
    - [x] https://github.com/SyliusLabs/PolyfillSymfonySecurity/pull/1 
    - [x] https://github.com/SyliusLabs/PolyfillSymfonySecurity/pull/2
    - [x] https://github.com/SyliusLabs/PolyfillSymfonySecurity/pull/3 
- [x] sylius/calendar
    - [x] Sylius/Calendar#9
- [x] sylius/mailer-bundle 🦀 
    - [x] Sylius/SyliusMailerBundle#102
    - [x] #Sylius/SyliusMailerBundle#145
- [x] sylius/resource-bundle ✅ Sylius/SyliusResourceBundle#400 (released in  "^1.10@alpha"
    - [x] Sylius/SyliusResourceBundle#471  
- [x] sylius/grid-bundle :heavy_check_mark:  Sylius/SyliusGridBundle#239 (released in "^1.12@alpha"
- [x] sylius/fixtures-bundle :heavy_check_mark: Sylius/SyliusFixturesBundle/pull/70
- [x] sylius/theme-bundle :heavy_check_mark:
    - [x] Sylius/SyliusThemeBundle#121 

### External Packages

- [x] babdev/pagerfanta-bundle ✅  https://github.com/BabDev/PagerfantaBundle/releases/tag/v3.4.0
- [x] behat/behat ✅ released
- [x] friendsofsymfony/rest-bundle ✅ https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/3.2.0
- [x] jms/serializer-bundle ✅ released (Requires Sylius to add support for ^4.0)
- [x] hwi/oauth-bundle ✅ released (on beta1)
- [x] knplabs/knp-menu-bundle ✅ released
- [x] lchrusciel/api-test-case ✅ released (https://github.com/lchrusciel/ApiTestCase/releases/tag/v5.2.0)
- [x] lexik/jwt-authentication-bundle ✅ released
- [x] payum/payum-bundle :heavy_check_mark: https://github.com/Payum/PayumBundle/releases/tag/2.5.0
- [x] phpspec/phpspec ✅ released
- [x] stof/doctrine-extensions-bundle ✅ https://github.com/stof/StofDoctrineExtensionsBundle/releases/tag/v1.7.0
- [x] winzou/state-machine ✅ [released](https://github.com/winzou/state-machine/releases/tag/0.4.3)
- [x] winzou/state-machine-bundle ✅ released

### Final fixes left:

- [x] Fix Static checks - https://github.com/Sylius/Sylius/pull/14326
- [x] Fix PHPSpec build - https://github.com/Sylius/Sylius/pull/14326
- [x] Fix PHPUnit tests - https://github.com/Sylius/Sylius/pull/14358
- [x] Fix non-js Behat scenarios - https://github.com/Sylius/Sylius/pull/14376
- [x] [Fix js Behat scenarios](Sylius/Sylius#14405) - https://github.com/Sylius/Sylius/pull/14405
- [x] Rebase `symfony-6` branch with 1.12 to upgrade the [main PR](Sylius/Sylius#13969)

**Comment by stloyd** [comment]
Pagerfanta got release [`3.4.0`](https://github.com/BabDev/PagerfantaBundle/blob/3.x/CHANGELOG.md#340-2021-11-09) with support for Symfony 6

**Comment by stloyd** [comment]
SyliusGridBundle: https://github.com/Sylius/SyliusGridBundle/pull/192 (but requires also: https://github.com/SyliusLabs/PolyfillSymfonyEventDispatcher/pull/1)

**Comment by mbabker** [comment]
friendsofsymfony/rest-bundle 🦀 https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2340
jms/serializer-bundle ✅  released (Requires Sylius to add support for `^4.0`)
knplabs/knp-menu-bundle ✅  released
lexik/jwt-authentication-bundle ✅  released
stof/doctrine-extensions-bundle ✅ https://github.com/stof/StofDoctrineExtensionsBundle/pull/431 (merged, pending release)
sylius/mailer-bundle 🦀 https://github.com/Sylius/SyliusMailerBundle/issues/5 (unless a final symfony/swiftmailer-bundle release is made with Symfony 6 support, Swift Mailer's EOL will be a very hard blocker)
winzou/state-machine-bundle 🦀

GridBundle also requires https://github.com/Sylius/SyliusGridBundle/pull/143 before https://github.com/Sylius/SyliusGridBundle/pull/192 can land (I'm not making PagerfantaBundle 2.x compatible with Symfony 6)

**Comment by loic425** [comment]
thanks @mbabker I edited the first post to update the informations.

**Comment by stloyd** [comment]
We have now:
- https://github.com/stof/StofDoctrineExtensionsBundle/releases/tag/v1.7.0

**Comment by loic425** [comment]
@stloyd thx, I updated the first post

**Comment by Roshyo** [comment]
@loic425 could you also add a reference to this: https://github.com/Sylius/Sylius/pull/13251 (remove MasterRequest calls when we switch to Symfony >6)

**Comment by loic425** [comment]
> @loic425 could you also add a reference to this: #13251 (remove MasterRequest calls when we switch to Symfony >5.3)

Added :) And I added Sylius/Sylius#13289 too

**Comment by Zales0123** [comment]
I've upgrade the issue description with `Final fixes left` section - we're really close to reach the goal 💪 🚀
