### ISSUE TITLE
[RFC] Finalizing translatable resources in Sylius

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4146]
Hello!

As part of the stabilization process, I want to finalize how translations are handled in Sylius. We have already made some steps towards that. What is left:

* Translation component and TranslationBundle are overhead to maintain and decoupling ResourceBundle from translations is quite annoying;
* AbstractTranslatable is not nice to use and all entities extending is not cool;
* Default and fallback locales are not handled correctly or at least not entirely clear how they should be defined;
* A2lixTranslationFormBundle is quite hacky and we should do something simpler to handle translations;
* Having all translatable fields rendered for all locales in a single view is not nice for more complex entities like Product.

Solutions (in order):

* [x] Translatable behavior for Resources will be optional, but as discussed in #3750 and started implementing in #3778, we should merge them;
* [x] Replace AbstractTranslatable with TranslatableTrait https://github.com/Sylius/Sylius/issues/2749;
* [x] Rework handling of default, current and fallback translation locale https://github.com/Sylius/Sylius/issues/4147;
* [x] Remove A2lixTranslationFormBundle and implement ``sylius_translations`` type, which will use standard ``collection`` type as parent. #4318

**Comment by pamil** [comment]
We also need to reconsider the approach for sorting translatable resources by a translated field, related issue: #3836

**Comment by lchrusciel** [comment]
Some of tasks are implemented already.
