### ISSUE TITLE
Use typehints introduced by PHP7+

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#8425]
A meta-issue to keep track of what needs to be done.

 - [ ] Global UPGRADE.md note about scalar and return typehints being introduced - @pamil
 - [x] Addressing / AddressingBundle - @pamil - #8325 
 - [x] AdminApiBundle - @Zales0123 - #8442
 - [x] AdminBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8454
 - [x] Attribute / AttributeBundle - @Zales0123 - #8427
 - [x] Channel / ChannelBundle - @pamil - #8421
 - [x] Core / CoreBundle - @Zales0123 - #8478 
 - [x] Currency / CurrencyBundle - @pamil - #8428
 - [x] Customer / CustomerBundle - @pamil - #8432
 - [x] FixturesBundle - @pamil - #8459
 - [x] Grid / GridBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8457
 - [x] Inventory / InventoryBundle - @Zales0123 - #8445 
 - [x] Locale / LocaleBundle - @pamil - #8430
 - [x] Mailer / MailerBundle - @Zales0123 - #8429
 - [x] MoneyBundle - @pamil - #8434
 - [x] Order / OrderBundle - @pamil - #8473
 - [x] Payment / PaymentBundle - @Zales0123 - #8425
 - [x] PayumBundle - @Zales0123 - #8444 
 - [x] Product / ProductBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8466
 - [x] Promotion / PromotionBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8436
 - [x] Registry - @pamil - #8433
 - [x] Resource / ResourceBundle - @pamil - #8439 
 - [x] Review / ReviewBundle - @Zales0123 - #8446 
 - [x] Shipping / ShippingBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8440
 - [x] ShopBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8453
 - [x] Taxation / TaxationBundle - @Zales0123 - https://github.com/Sylius/Sylius/pull/8451
 - [x] Taxonomy / TaxonomyBundle - @pamil - #8447 
 - [x] ThemeBundle - @pamil - #8450
 - [x] User / UserBundle - @pamil - #8458
 - [x] UiBundle - @pamil - #8448

**Comment by TomasVotruba** [comment]
I wonder... do you do this manually or do you use tool like [Slevomat/TypeHintSniff](https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintstypehintdeclaration-)?
