### ISSUE TITLE
The Events, Reloaded.

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#879]
I've created a wiki page with most of events involved in the order creation. Let's try to make them clear.

https://github.com/Sylius/Sylius/wiki/Events

Please try to have a look and share your thoughts on how to improve it. I start (and will add your ideas in this list):
  - [x] Unify method names. We currently mix `onCartChange` and `process` for method names of listeners. We should unify them, choosing a meaningful name instead of the event name (because it can be reused in several events). Done in #883 
  - [ ] Create our own Event class. Let's get rid of all these `if ($event->getSubject() instanceof Order)`! WIP in #774 
  - [ ] Use 2 clearly identified family of events: `checkout` on one side, `order creation` on the other side. For example, `OrderPromotionListener::processOrderPromotion` is listening at `addressing.pre_complete` but it has actually nothing to do with the checkout process. It just applies promotion. To achieve that, we should dispatch at each checkout step 2 events: `order_set_address` and `checkout_addressing`. And listeners listen the event they want.
  - [x] We must change where `order.pre_create` is dispatched. It's currently on finalize step, but it should be on payment received! Actually we should differenciate 2 states: order created (it gets a number, inventory unit stocks are decreased) and order paid (shipments are set to ready so that they can be shipped, etc). WIP in #899 
  - [ ] Your ideas!
