### ISSUE TITLE
More flexible password hashing

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#9560]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

Our currently used, default password hashing algorithm is `sha512`, which shouldn't be used anymore and it has been already mentioned in issues like #3045.

My proposed solution would be to provide a general framework that would make changing password hashing algorithm much easier. The solution can be as simple as:

 - adding the `hashingAlgorithm` field to user models
 - resolving `Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface` instance used to hash passwords based on that field
 - to provide a seamless upgrade path, rehashing the password using the current hashing algorithm when a user logs in

Since it's a new feature targeted to `master` branch being the next `v1.3.0` release, which also requires at least PHP 7.2, we can jump straight into the world of modern cryptography and use [`libsodium`](https://paragonie.com/book/pecl-libsodium), which is distributed with PHP since 7.2 release.

Further improvements might include adding a grace period after which users are obliged to reset their passwords (so that you wouldn't have to store `sha512`-hashed passwords years after you changed the hashing algorithm), but it is not a part of this RFC.

Checklist:
 - [x] Support for multiple password encoders at once (#10008, #10080)
 - [x] Argon2i used for new users while sha512 kept for old users (#10080)
 - [x] Seamless encoders changes - listening for login event, rehashing the password then (#10084)
 - [x] Integration tests in Sylius as an application (#10084)

**Comment by teohhanhui** [comment]
For the default, we should use `argon2i` as it ships with PHP 7.2.

https://symfony.com/blog/new-in-symfony-3-4-argon2i-password-hasher

**Comment by psren** [comment]
> Further improvements might include adding a grace period after which users are obliged to reset their passwords (so that you wouldn't have to store sha512-hashed passwords years after you changed the hashing algorithm), but it is not a part of this RFC.

Maybe this can be replaced by an "upgrade" command which encodes the already encoded password?

e.g. the pass is stores as hashed sha512 it could "rehash" the password.
and store the hashing algos as csv (e.g. ```hashingAlgorithm``` => ```sha512,argon2i```)
Then a ```ChainEncoder``` could run both ```PasswordEncoderInterface``` in serial.

Benefit is that a one-time upgrade of all passwords would be possible without annoying the users.
Down-Side: Hashing and comparing would be slightly slower.

**Comment by pamil** [comment]
I'm afraid it would only give a false sense of security because [collision resistance](https://en.wikipedia.org/wiki/Collision_resistance) stays the same at best - if `sha512` is broken, then additional `argon2i` won't help.

**Comment by teohhanhui** [comment]
Maybe something like this: https://tideways.com/profiler/blog/migrating-users-to-new-password-hashing-algorithms-in-symfony

**Comment by teohhanhui** [comment]
Hmm... Actually since the `sodium` extension is bundled since PHP 7.2, and since `argon2id` has been the default since `libsodium` 1.0.15:

https://github.com/jedisct1/libsodium/blob/7cdf3f0e8419aa1be306effd11a20d980c118e04/ChangeLog#L27-L28

So perhaps we could require `ext-sodium` and jump straight to `argon2id`, which will be available (without the `sodium` extension) in PHP 7.3 anyway.

**Comment by teohhanhui** [comment]
See also https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2788

**Comment by kortwotze** [comment]
Just as an aside: Why don't we make the ShopUser entity implement `EncoderAwareInterface` and let configuration choose the password encoder per implemented ShopUser class?
